"""
Alembic environment configuration for District Console.

Applies SQLite-specific pragmas (WAL mode, FK enforcement, synchronous=NORMAL)
on every connection to ensure consistent behaviour across migrations and
normal application operation.

ORM model metadata is imported here so Alembic can generate autogenerated
migrations in future prompts when SQLAlchemy ORM models are defined.
"""
from __future__ import annotations

import logging
import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, event, text

# Alembic Config object — provides access to alembic.ini values
config = context.config

# Configure Python logging from alembic.ini if present
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

logger = logging.getLogger("alembic.env")

# ---------------------------------------------------------------------------
# ORM metadata — imported from the infrastructure layer once ORM models exist
# (Prompt 3+). Currently None so offline migrations work without ORM models.
# ---------------------------------------------------------------------------
try:
    from district_console.infrastructure.orm import Base  # type: ignore[import]
    target_metadata = Base.metadata
except ImportError:
    target_metadata = None


def get_db_url() -> str:
    """Resolve the database URL from environment or alembic.ini."""
    db_path = os.environ.get(
        "DC_DB_PATH",
        os.path.join(os.getcwd(), "data", "district.db"),
    )
    return f"sqlite+aiosqlite:///{db_path}"


def _apply_sqlite_pragmas(dbapi_conn, connection_record) -> None:  # noqa: ANN001
    """
    Apply SQLite performance and correctness pragmas to every connection.

    WAL mode:     Concurrent readers without blocking writers.
    FK enforcement: Enforces FOREIGN KEY constraints (off by default in SQLite).
    synchronous:  NORMAL balances durability and write throughput.
    busy_timeout: Wait up to 5 seconds before raising SQLITE_BUSY.
    """
    cursor = dbapi_conn.cursor()
    cursor.execute("PRAGMA journal_mode=WAL")
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.execute("PRAGMA synchronous=NORMAL")
    cursor.execute("PRAGMA busy_timeout=5000")
    cursor.close()


def run_migrations_offline() -> None:
    """
    Run migrations without an active database connection.

    Produces SQL scripts suitable for manual review or execution.
    """
    url = get_db_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,  # Required for SQLite ALTER TABLE support
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database connection."""
    url = get_db_url()
    connectable = create_engine(url, echo=False)

    # Attach the pragma hook before any connection is made
    event.listen(connectable, "connect", _apply_sqlite_pragmas)

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,  # Required for SQLite ALTER TABLE support
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
